apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-qwen3-32b
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vllm-qwen3-32b
  template:
    metadata:
      labels:
        app: vllm-qwen3-32b
        inference.networking.k8s.io/engine-type: vllm
    spec:
      containers:
        - name: lora
          image: "public.ecr.aws/q9t5s3a7/vllm-cpu-release-repo:v0.10.2" # formal images can be found in https://gallery.ecr.aws/q9t5s3a7/vllm-cpu-release-repo
          imagePullPolicy: Always
          command: ["python3", "-m", "vllm.entrypoints.openai.api_server"]
          args:
          - "--model"
          - "Qwen/Qwen3-32B"
          - "--port"
          - "8000"
          - "--enable-lora"
          - "--max-loras"
          - "4"
          - "--max-model-len"
          - "16384"
          env:
            - name: PORT
              value: "8000"
            - name: VLLM_ALLOW_RUNTIME_LORA_UPDATING
              value: "true"
            - name: VLLM_CPU_KVCACHE_SPACE
              value: "4"
            - name: VLLM_PLUGINS
              value: "lora_filesystem_resolver"
            - name: VLLM_LORA_RESOLVER_CACHE_DIR
              value: "/adapters"
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
          livenessProbe:
            failureThreshold: 240
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 600
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources:
             limits:
               cpu: "16"
               memory: "100Gi"
               ephemeral-storage: "100Gi"
             requests:
               cpu: "16"
               memory: "100Gi"
               ephemeral-storage: "100Gi"
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /dev/shm
              name: shm
            - name: adapters
              mountPath: "/adapters"
      initContainers:
        - name: pull-lora
          image: alpine/git
          command: ["/bin/sh", "-c"]
          args:
          - |
            mkdir -p /adapters/small-segment-lora
            mkdir -p /adapters/cad-fabricator
            git clone --depth 1 https://huggingface.co/ttt421/nec119-small-segment-lora /adapters/small-segment-lora
            git clone --depth 1 https://huggingface.co/SriSanth2345/Qwen-1.5B-Tweet-Generations /adapters/cad-fabricator
          volumeMounts:
            - name: adapters
              mountPath: /adapters
          resources:
            limits:
              ephemeral-storage: "10Gi"
            requests:
              ephemeral-storage: "10Gi"
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - name: data
          emptyDir: {}
        - name: shm
          emptyDir:
            medium: Memory
        - name: adapters
          emptyDir: {}
