/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	apixv1alpha2 "sigs.k8s.io/gateway-api-inference-extension/apix/v1alpha2"
)

// InferenceObjectiveLister helps list InferenceObjectives.
// All objects returned here must be treated as read-only.
type InferenceObjectiveLister interface {
	// List lists all InferenceObjectives in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apixv1alpha2.InferenceObjective, err error)
	// InferenceObjectives returns an object that can list and get InferenceObjectives.
	InferenceObjectives(namespace string) InferenceObjectiveNamespaceLister
	InferenceObjectiveListerExpansion
}

// inferenceObjectiveLister implements the InferenceObjectiveLister interface.
type inferenceObjectiveLister struct {
	listers.ResourceIndexer[*apixv1alpha2.InferenceObjective]
}

// NewInferenceObjectiveLister returns a new InferenceObjectiveLister.
func NewInferenceObjectiveLister(indexer cache.Indexer) InferenceObjectiveLister {
	return &inferenceObjectiveLister{listers.New[*apixv1alpha2.InferenceObjective](indexer, apixv1alpha2.Resource("inferenceobjective"))}
}

// InferenceObjectives returns an object that can list and get InferenceObjectives.
func (s *inferenceObjectiveLister) InferenceObjectives(namespace string) InferenceObjectiveNamespaceLister {
	return inferenceObjectiveNamespaceLister{listers.NewNamespaced[*apixv1alpha2.InferenceObjective](s.ResourceIndexer, namespace)}
}

// InferenceObjectiveNamespaceLister helps list and get InferenceObjectives.
// All objects returned here must be treated as read-only.
type InferenceObjectiveNamespaceLister interface {
	// List lists all InferenceObjectives in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apixv1alpha2.InferenceObjective, err error)
	// Get retrieves the InferenceObjective from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apixv1alpha2.InferenceObjective, error)
	InferenceObjectiveNamespaceListerExpansion
}

// inferenceObjectiveNamespaceLister implements the InferenceObjectiveNamespaceLister
// interface.
type inferenceObjectiveNamespaceLister struct {
	listers.ResourceIndexer[*apixv1alpha2.InferenceObjective]
}
