GatewayAPIInferenceExtensionVersion: v1.1.0
apiVersion: gateway.networking.k8s.io/v1
date: "2026-01-29T23:03:15Z"
gatewayAPIChannel: experimental
gatewayAPIVersion: v1.4.1
implementation:
  contact:
  - https://github.com/nginx/nginx-gateway-fabric/discussions/new/choose
  organization: nginx
  project: nginx-gateway-fabric
  url: https://github.com/nginx/nginx-gateway-fabric
  version: v2.4.0
kind: ConformanceReport
mode: default
profiles:
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 10
      Skipped: 0
  name: Gateway
  summary: Core tests succeeded.
