/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
	apixv1alpha1 "sigs.k8s.io/gateway-api-inference-extension/apix/v1alpha1"
	v1 "sigs.k8s.io/gateway-api-inference-extension/client-go/applyconfiguration/api/v1"
)

// ImportControllerApplyConfiguration represents a declarative configuration of the ImportController type for use
// with apply.
type ImportControllerApplyConfiguration struct {
	Name              *apixv1alpha1.ControllerName         `json:"name,omitempty"`
	ExportingClusters []ExportingClusterApplyConfiguration `json:"exportingClusters,omitempty"`
	Parents           []v1.ParentStatusApplyConfiguration  `json:"parents,omitempty"`
	Conditions        []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// ImportControllerApplyConfiguration constructs a declarative configuration of the ImportController type for use with
// apply.
func ImportController() *ImportControllerApplyConfiguration {
	return &ImportControllerApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ImportControllerApplyConfiguration) WithName(value apixv1alpha1.ControllerName) *ImportControllerApplyConfiguration {
	b.Name = &value
	return b
}

// WithExportingClusters adds the given value to the ExportingClusters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExportingClusters field.
func (b *ImportControllerApplyConfiguration) WithExportingClusters(values ...*ExportingClusterApplyConfiguration) *ImportControllerApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithExportingClusters")
		}
		b.ExportingClusters = append(b.ExportingClusters, *values[i])
	}
	return b
}

// WithParents adds the given value to the Parents field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Parents field.
func (b *ImportControllerApplyConfiguration) WithParents(values ...*v1.ParentStatusApplyConfiguration) *ImportControllerApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithParents")
		}
		b.Parents = append(b.Parents, *values[i])
	}
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ImportControllerApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *ImportControllerApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
