GatewayAPIInferenceExtensionVersion: v1.4.0
apiVersion: gateway.networking.k8s.io/v1
date: "2026-03-20T05:14:59Z"
gatewayAPIChannel: experimental
gatewayAPIVersion: v1.5.0
implementation:
  contact:
  - github.com/agentgateway/agentgateway/issues/new/choose
  organization: agentgateway
  project: agentgateway
  url: github.com/agentgateway/agentgateway
  version: v1.0.0
kind: ConformanceReport
mode: default
profiles:
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 12
      Skipped: 0
  name: Gateway
  summary: Core tests succeeded.
