/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	apixv1alpha1 "sigs.k8s.io/gateway-api-inference-extension/apix/v1alpha1"
)

// InferencePoolImportLister helps list InferencePoolImports.
// All objects returned here must be treated as read-only.
type InferencePoolImportLister interface {
	// List lists all InferencePoolImports in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apixv1alpha1.InferencePoolImport, err error)
	// InferencePoolImports returns an object that can list and get InferencePoolImports.
	InferencePoolImports(namespace string) InferencePoolImportNamespaceLister
	InferencePoolImportListerExpansion
}

// inferencePoolImportLister implements the InferencePoolImportLister interface.
type inferencePoolImportLister struct {
	listers.ResourceIndexer[*apixv1alpha1.InferencePoolImport]
}

// NewInferencePoolImportLister returns a new InferencePoolImportLister.
func NewInferencePoolImportLister(indexer cache.Indexer) InferencePoolImportLister {
	return &inferencePoolImportLister{listers.New[*apixv1alpha1.InferencePoolImport](indexer, apixv1alpha1.Resource("inferencepoolimport"))}
}

// InferencePoolImports returns an object that can list and get InferencePoolImports.
func (s *inferencePoolImportLister) InferencePoolImports(namespace string) InferencePoolImportNamespaceLister {
	return inferencePoolImportNamespaceLister{listers.NewNamespaced[*apixv1alpha1.InferencePoolImport](s.ResourceIndexer, namespace)}
}

// InferencePoolImportNamespaceLister helps list and get InferencePoolImports.
// All objects returned here must be treated as read-only.
type InferencePoolImportNamespaceLister interface {
	// List lists all InferencePoolImports in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apixv1alpha1.InferencePoolImport, err error)
	// Get retrieves the InferencePoolImport from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apixv1alpha1.InferencePoolImport, error)
	InferencePoolImportNamespaceListerExpansion
}

// inferencePoolImportNamespaceLister implements the InferencePoolImportNamespaceLister
// interface.
type inferencePoolImportNamespaceLister struct {
	listers.ResourceIndexer[*apixv1alpha1.InferencePoolImport]
}
